"""empty message

Revision ID: 30546ff474ab
Revises: 1e2ee806b334
Create Date: 2025-08-10 17:14:13.084575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30546ff474ab'
down_revision = '1e2ee806b334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(collation='utf8mb4_is_0900_ai_ci', length=200),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_is_0900_ai_ci', length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
