"""message

Revision ID: 354a5e15b4e4
Revises: 3e6b59020dad
Create Date: 2025-08-08 12:37:49.531274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '354a5e15b4e4'
down_revision = '3e6b59020dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('msg',
               existing_type=mysql.VARCHAR(collation='utf8mb4_is_0900_ai_ci', length=120),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('msg',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_is_0900_ai_ci', length=120),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
