"""empty message

Revision ID: 90db48a7e6cd
Revises: 30546ff474ab
Create Date: 2025-08-10 22:51:22.943464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90db48a7e6cd'
down_revision = '30546ff474ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_file', sa.String(length=50), nullable=False))
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_is_0900_ai_ci', length=80),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_is_0900_ai_ci', length=80),
               existing_nullable=False)
        batch_op.drop_column('img_file')

    # ### end Alembic commands ###
