"""Add deleted_at column to Post

Revision ID: b6990a2c7261
Revises: ad953326b37f
Create Date: 2025-08-13 18:34:18.991765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6990a2c7261'
down_revision = 'ad953326b37f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
