"""update mobile data type

Revision ID: db70cd44f4e1
Revises: 8117c11ed158
Create Date: 2025-08-08 17:41:40.175938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db70cd44f4e1'
down_revision = '8117c11ed158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('mobile',
               existing_type=mysql.VARCHAR(collation='utf8mb4_is_0900_ai_ci', length=12),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('mobile',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(collation='utf8mb4_is_0900_ai_ci', length=12),
               existing_nullable=False)

    # ### end Alembic commands ###
